site_name: SBD1 Digimon

repo_name: "SBD1 Digimon Rep"
repo_url: "https://github.com/SBD1/2022.2-Grupo8-Digimon"

theme:
    name: material
    language: pt
    features:
        - navigation.tabs
        - navigation.expand
    font:
        text: Poppins
        code: Roboto Mono
      
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences

extra_css:
    - assets/stylesheets/styles.css

nav:
    - Home: index.md
    - Módulo 1:
        - Diagrama Entidade Relacionamento (DER): modulo_1/diagrama_entidade_relacionamento.md
        - Diagrama Relacional: modulo_1/diagrama_relacional.md
        - Dicionário de Dados: modulo_1/dicionario_de_dados.md
        - Apresentação: modulo_1/apresentacao/modulo_1.md
    - Módulo 2:
        - Apresentação: modulo_2/modulo_2.md